### PR TITLE
commented roles

### PR DESCRIPTION
**Pull request by skoulouzis**

### CODE REVIEW

**Comment by longcui** [comment]
@skoulouzis Could you please let us know why you would like to comment it out? thanks

**Comment by skoulouzis** [comment]
This was not working for ansible 2.9.9.

**Comment by anandhakumarpalanisamy** [comment]
Hi @skoulouzis , 

I believe the following lines are mandatory :
`  roles:
     - gluster.infra`

Kindly test with the latest master branch, and let us know if the error persists.

**Comment by anandhakumarpalanisamy** [comment]
Had discussion with spiros . Spiros specified that  there is no need for the merge. He suggested to close this pull request.

**Pull request closed without merging**
